version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: npm i
      - save_cache:
          paths:
            - /src/node_modules
          key: "npm-packages"
      - run: npm run lint
  
  test:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: 
            - "npm-packages"
      - run: npm i
      - run: npm test
  
  analyze:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: npm audit

  create-infra:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: creates or updates the stack if it exists
          command: |
            aws cloudformation deploy \
              --template-file infra.yml \
              --stack-name my-stack

      

workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - create-infra
      # - build
      # - test:
      #     requires:
      #       - build
      # - analyze:
      #     requires:
      #       - test
